name: flutter_qr_reader
description: QR code (scan QRCode and picture) recognition （AndroidView/UiKitView）
version: 1.0.3
author: 王贺天<hetian@hetian.me>
homepage: https://github.com/hetian9288/flutter_qr_reader

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.hetian.flutter_qr_reader
    pluginClass: FlutterQrReaderPlugin